const $=s=>document.querySelector(s);
const tabs=[...document.querySelectorAll('.tab')];tabs.forEach(t=>t.onclick=()=>{tabs.forEach(x=>x.classList.toggle('active',x===t));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===t.dataset.tab))});
for(let i=0;i<28;i++){const x=document.createElement('i');x.style.animationDelay=(i*.035)+'s';x.style.animationDuration=(.3+Math.random()*.45)+'s';$('#wave').appendChild(x)}
const enc=new TextEncoder(),dec=new TextDecoder();const MAX_FILE=256*1024,FREQS=[900,1300,1700,2100],LEADER=2500,SYNC=[3,0,3,1,2,0,1,3,2,1,0,2],END=[0,3,0,2,1,3,2,0,1,2,3,1];let chosen=null,txCtx=null,txNode=null,sending=false;
function fmt(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(2)+' MB'}
function eta(bytes,ms){const repeat=ms>=35?3:ms>=20?2:1,sec=(bytes+80)*4*ms*repeat/1000+2;if(sec<60)return Math.ceil(sec)+'초';return Math.floor(sec/60)+'분 '+Math.ceil(sec%60)+'초'}
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function u32be(n){return[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255]}function readU32(a,o){return((a[o]<<24)>>>0)+(a[o+1]<<16)+(a[o+2]<<8)+a[o+3]}
async function buildPacket(file){const name=enc.encode(file.name),mime=enc.encode(file.type||'application/octet-stream');if(file.size>MAX_FILE)throw Error('최대 256 KB까지 전송할 수 있습니다.');const p=new Uint8Array(await file.arrayBuffer()),h=new Uint8Array([87,77,70,50,name.length,mime.length,...u32be(p.length)]),a=new Uint8Array(h.length+name.length+mime.length+p.length+4);let o=0;a.set(h,o);o+=h.length;a.set(name,o);o+=name.length;a.set(mime,o);o+=mime.length;a.set(p,o);a.set(u32be(crc32(p)),a.length-4);return a}
function refresh(){chosen=$('#file').files?.[0]||null;$('#sendBtn').disabled=!chosen;if(!chosen)return;$('#fileName').textContent=chosen.name;$('#fileInfo').textContent=fmt(chosen.size)+' · '+(chosen.type||'알 수 없는 형식')+(chosen.size>MAX_FILE?' · 256 KB 초과':'');$('#eta').textContent=eta(chosen.size,+$('#speed').value)}$('#file').onchange=refresh;$('#file').oninput=refresh;$('#speed').onchange=refresh;
$('#sendBtn').onclick=async()=>{if(!chosen||sending)return;try{const A=window.AudioContext||window.webkitAudioContext,packet=await buildPacket(chosen);txCtx=new A();await txCtx.audioWorklet.addModule('./modem-worklet.js');await txCtx.resume();txNode=new AudioWorkletNode(txCtx,'modem-modulator');txNode.connect(txCtx.destination);txNode.port.onmessage=e=>{if(e.data.type==='progress'){const p=Math.round(e.data.done/e.data.total*100);$('#sendPct').textContent=p+'%';$('#sendBar').style.width=p+'%';$('#sendState').textContent='오류정정 데이터 전송 중'}if(e.data.type==='ending')$('#sendState').textContent='종료 프레임 전송 완료';if(e.data.type==='done')finishSend(true)};sending=true;$('#sendBox').classList.remove('hidden');$('#stopSendBtn').classList.remove('hidden');$('#sendBtn').classList.add('hidden');$('#sendState').textContent='동기화 신호 전송 중';const copy=packet.slice();txNode.port.postMessage({type:'start',bytes:copy.buffer,symbolMs:+$('#speed').value},[copy.buffer])}catch(e){showErr('전송 실패: '+e.message);finishSend(false)}};
$('#stopSendBtn').onclick=()=>finishSend(false);function finishSend(ok){try{txNode?.port.postMessage({type:'stop'});txCtx?.close()}catch{}txNode=txCtx=null;sending=false;$('#stopSendBtn').classList.add('hidden');$('#sendBtn').classList.remove('hidden');if(ok){$('#sendPct').textContent='100%';$('#sendBar').style.width='100%';$('#sendState').textContent='전송 완료'}}
let rxCtx=null,rxNode=null,rxStream=null,rxSilent=null,receiving=false,phase='leader',leaderHits=0,syncBuf=[],endBuf=[],symbolSamples=0,sampleBuf=[],dibits=[],decoded=[],expectedTotal=null,repeat=1;
function go(a,f,sr,s=0,e=a.length){const N=e-s;if(N<8)return 0,k=Math.round(N*f/sr),w=2*Math.PI*k/N,c=2*Math.cos(w);let a0=0,a1=0,a2=0;for(let i=s;i<e;i++){a0=a[i]+c*a1-a2;a2=a1;a1=a0}return a1*a1+a2*a2-c*a1*a2}function rms(a){let s=0;for(const x of a)s+=x*x;return Math.sqrt(s/a.length)}
function energies(a,sr){return FREQS.map(f=>go(a,f,sr))}function bestTone(a,sr){const es=energies(a,sr),sorted=es.map((v,i)=>[v,i]).sort((a,b)=>b[0]-a[0]);return{idx:sorted[0][1],freq:FREQS[sorted[0][1]],confidence:sorted[0][0]/Math.max(1e-12,sorted[1][0])}}
function resetRx(){phase='leader';leaderHits=0;syncBuf=[];endBuf=[];sampleBuf=[];dibits=[];decoded=[];expectedTotal=null;$('#rxBytes').textContent='0 B';$('#rxPhase').textContent='잡음 필터링 · 시작음 탐색';$('#rxFreq').textContent='— Hz';$('#result').classList.add('hidden');$('#errorBox').classList.add('hidden')}
$('#rxBtn').onclick=async()=>{if(receiving){stopRx();return}resetRx();try{rxStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false,channelCount:1}});const A=window.AudioContext||window.webkitAudioContext;rxCtx=new A();await rxCtx.audioWorklet.addModule('./modem-worklet.js');await rxCtx.resume();const src=rxCtx.createMediaStreamSource(rxStream);rxNode=new AudioWorkletNode(rxCtx,'modem-capture');rxSilent=rxCtx.createGain();rxSilent.gain.value=0;src.connect(rxNode);rxNode.connect(rxSilent).connect(rxCtx.destination);rxNode.port.onmessage=e=>processChunk(new Float32Array(e.data));symbolSamples=Math.round(rxCtx.sampleRate*(+$('#rxSpeed').value)/1000);repeat=+$('#rxSpeed').value>=35?3:+$('#rxSpeed').value>=20?2:1;receiving=true;$('#rxBtn').textContent='수신 중지';$('#rxBox').classList.remove('hidden');$('#rxRing').classList.add('listening');$('#rxState').textContent='잡음 감시 중';$('#rxDesc').textContent='사람 목소리는 무시하고 Web Modem 신호를 찾습니다.'}catch(e){showErr('마이크 실패: '+e.message)}};
function stopRx(){receiving=false;rxStream?.getTracks().forEach(t=>t.stop());try{rxCtx?.close()}catch{}rxCtx=rxNode=rxStream=rxSilent=null;$('#rxBtn').textContent='수신 시작';$('#rxRing').classList.remove('listening')}
function processChunk(a){if(!receiving||!rxCtx)return;const level=rms(a),db=level>1e-8?20*Math.log10(level):-Infinity;$('#rxLevel').textContent=isFinite(db)?db.toFixed(0)+' dB':'-∞ dB';$('#rxBar').style.width=Math.max(0,Math.min(100,(db+60)/60*100))+'%';if(phase==='leader'){const es=energies(a,rxCtx.sampleRate),le=go(a,LEADER,rxCtx.sampleRate),bt=bestTone(a,rxCtx.sampleRate),mx=es.reduce((x,y)=>Math.max(x,y),0);$('#rxFreq').textContent=(le>1.25*mx?LEADER:bt.freq)+' Hz';if(level>.003&&le>1.25*mx)leaderHits++;else leaderHits=Math.max(0,leaderHits-1);if(leaderHits>=6){phase='sync';sampleBuf=[];$('#rxPhase').textContent='동기화 패턴 탐색';$('#rxState').textContent='모뎀 신호 감지'}}else{sampleBuf.push(...a);decodeSymbols()}}
function decodeSymbols(){while(sampleBuf.length>=symbolSamples){const a=Float32Array.from(sampleBuf.slice(0,symbolSamples));sampleBuf=sampleBuf.slice(symbolSamples);const b=bestTone(a,rxCtx.sampleRate);$('#rxFreq').textContent=b.freq+' Hz';if(phase==='sync'){if(b.confidence<1.18)continue;syncBuf.push(b.idx);if(syncBuf.length>SYNC.length)syncBuf.shift();if(syncBuf.length===SYNC.length&&syncBuf.every((v,i)=>v===SYNC[i])){phase='data';dibits=[];decoded=[];$('#rxPhase').textContent='오류정정 데이터 수신';$('#rxState').textContent='파일 수신 중'}}else if(phase==='data'){dibits.push(b.idx);if(dibits.length===4*repeat){let out=0;for(let q=0;q<4;q++){const votes=[0,0,0,0];for(let r=0;r<repeat;r++)votes[dibits[q*repeat+r]]++;let bi=0;for(let j=1;j<4;j++)if(votes[j]>votes[bi])bi=j;out|=bi<<(6-q*2)}decoded.push(out);dibits=[];$('#rxBytes').textContent=fmt(decoded.length);if(decoded.length===4&&!(decoded[0]===87&&decoded[1]===77&&decoded[2]===70&&decoded[3]===50)){showErr('동기화 후 헤더 오류입니다. 안정적 모드로 다시 시도하세요.');stopRx();return}if(decoded.length===10){const n=decoded[4],m=decoded[5],z=readU32(decoded,6);if(z>MAX_FILE){showErr('헤더 손상 감지');stopRx();return}expectedTotal=10+n+m+z+4}if(expectedTotal&&decoded.length===expectedTotal){phase='end';endBuf=[];$('#rxPhase').textContent='종료 프레임 확인 중';$('#rxState').textContent='마무리 확인 중'}}}else if(phase==='end'){if(b.confidence<1.12)continue;endBuf.push(b.idx);if(endBuf.length>END.length)endBuf.shift();if(endBuf.length===END.length&&endBuf.every((v,i)=>v===END[i])){finishRx();return}}}}
function finishRx(){const a=Uint8Array.from(decoded.slice(0,expectedTotal)),nl=a[4],ml=a[5],size=readU32(a,6);let o=10,name=dec.decode(a.slice(o,o+nl));o+=nl;const mime=dec.decode(a.slice(o,o+ml));o+=ml;const payload=a.slice(o,o+size);o+=size;if(readU32(a,o)!==crc32(payload)){showErr('CRC 오류: 종료 프레임은 확인했지만 데이터 일부가 손상되었습니다. 안정적 모드로 다시 전송하세요.');stopRx();return}const url=URL.createObjectURL(new Blob([payload],{type:mime||'application/octet-stream'}));$('#download').href=url;$('#download').download=name||'received.bin';$('#resultName').textContent=name;$('#resultMeta').textContent=fmt(size)+' · '+mime;$('#result').classList.remove('hidden');$('#rxState').textContent='수신 완료';$('#rxDesc').textContent='종료 프레임, 반복 오류정정, CRC 검사를 모두 통과했습니다.';stopRx()}
function showErr(m){$('#errorBox').textContent=m;$('#errorBox').classList.remove('hidden')}
