(()=>{
const $=s=>document.querySelector(s),T=window.FaxT30,R=window.FaxRx;
const F={ctx:null,stream:null,src:null,node:null,silent:null,scriptNode:null,role:null,state:'idle',timer:null,osc:null,gain:null,decoder:null,cng:0,ced:0,file:null,page:null,busy:false,rxCapture:null,decodePromise:null,pendingPage:null,receivedUrl:null,disRetry:null};
function setState(t,d){$('#faxState').textContent=t;$('#faxDesc').textContent=d||''}
function log(t){const el=$('#faxLog'),r=document.createElement('div');r.textContent=new Date().toLocaleTimeString()+' · '+t;el.prepend(r);while(el.children.length>24)el.lastChild.remove()}
function energy(a,sr,f){let re=0,im=0;for(let i=0;i<a.length;i++){const w=2*Math.PI*f*i/sr;re+=a[i]*Math.cos(w);im-=a[i]*Math.sin(w)}return re*re+im*im}
function micStatus(text){const el=$('#faxMic');if(el)el.textContent=text}
async function openAudio(){if(F.ctx&&F.stream?.getAudioTracks()?.some(t=>t.readyState==='live'))return;if(!navigator.mediaDevices?.getUserMedia)throw Error('이 브라우저는 마이크 입력을 지원하지 않습니다. HTTPS에서 실행하세요.');micStatus('마이크: 여는 중');log('마이크 요청 시작');let stream;try{stream=await navigator.mediaDevices.getUserMedia({audio:true})}catch(e){micStatus('마이크: 실패');log('마이크 요청 실패 · '+e.name);throw Error(`마이크를 열 수 없습니다 (${e.name}: ${e.message})`)}const track=stream.getAudioTracks()[0];if(!track||track.readyState!=='live'){stream.getTracks().forEach(t=>t.stop());micStatus('마이크: 비활성');throw Error('마이크 트랙이 활성 상태가 아닙니다.')}F.stream=stream;micStatus('마이크: 활성');log(`마이크 활성 · ${track.label||'기본 마이크'}`);track.onended=()=>{micStatus('마이크: 종료됨');log('마이크 트랙 종료')};track.onmute=()=>{micStatus('마이크: 음소거됨');log('브라우저가 마이크 입력을 음소거함')};track.onunmute=()=>{micStatus('마이크: 활성');log('마이크 입력 재개')};const A=window.AudioContext||window.webkitAudioContext;F.ctx=new A();await F.ctx.resume();F.src=F.ctx.createMediaStreamSource(F.stream);F.decoder=new T.V21Decoder(F.ctx.sampleRate,onFrame);try{await F.ctx.audioWorklet.addModule('./modem-worklet.js');F.node=new AudioWorkletNode(F.ctx,'modem-capture');F.silent=F.ctx.createGain();F.silent.gain.value=0;F.src.connect(F.node);F.node.connect(F.silent).connect(F.ctx.destination);F.node.port.onmessage=e=>onAudio(new Float32Array(e.data));log('오디오 입력 엔진: AudioWorklet')}catch(e){log('AudioWorklet 실패 · ScriptProcessor 폴백');F.scriptNode=F.ctx.createScriptProcessor(1024,1,1);F.silent=F.ctx.createGain();F.silent.gain.value=0;F.src.connect(F.scriptNode);F.scriptNode.connect(F.silent).connect(F.ctx.destination);F.scriptNode.onaudioprocess=e=>onAudio(new Float32Array(e.inputBuffer.getChannelData(0)))}await new Promise(r=>setTimeout(r,120));if(track.readyState!=='live')throw Error('마이크가 열린 직후 종료되었습니다.')}
function onAudio(a){if(!F.ctx)return;F.rxCapture?.push(a);const sr=F.ctx.sampleRate,e11=energy(a,sr,1100),e21=energy(a,sr,2100),tot=Math.max(1e-9,a.reduce((s,v)=>s+v*v,0));if(e11/tot>60)F.cng++;else F.cng=Math.max(0,F.cng-1);if(e21/tot>60)F.ced++;else F.ced=Math.max(0,F.ced-1);if(F.ced===5&&F.role==='tx'){log('CED 2100 Hz 응답 감지');setState('상대 팩스 응답','DIS 제어 프레임을 기다립니다.')}if(F.cng===5&&F.role==='rx'){log('CNG 1100 Hz 호출 감지');$('#faxFreq').textContent='1100 Hz CNG'}F.decoder?.push(a)}
function stopTone(){clearInterval(F.timer);F.timer=null;try{F.osc?.stop()}catch{}F.osc=null}
function stopDisRetry(){if(F.disRetry){clearTimeout(F.disRetry);F.disRetry=null}}
function tone(freq,sec=.5){return new Promise(res=>{const o=F.ctx.createOscillator(),g=F.ctx.createGain();F.osc=o;F.gain=g;o.frequency.value=freq;g.gain.value=.3;o.connect(g).connect(F.ctx.destination);o.onended=()=>{if(F.osc===o)F.osc=null;if(F.gain===g)F.gain=null;res()};o.start();o.stop(F.ctx.currentTime+sec)})}
function delay(ms){return new Promise(r=>setTimeout(r,ms))}
async function prepareFile(file){F.file=file;$('#faxFileName').textContent=file.name;$('#faxFileMeta').textContent=(file.type||'알 수 없음')+' · '+Math.ceil(file.size/1024)+' KB · 변환 중';setState('문서 변환 중','팩스용 1728px 흑백 T.4 MH 페이지를 만들고 있습니다.');try{F.page=await T.imageToMH(file);$('#faxFileMeta').textContent=`T.4 MH · ${F.page.width}×${F.page.height} · ${Math.ceil(F.page.bits.length/8/1024)} KB`;log(`페이지 준비 완료 ${F.page.width}×${F.page.height}`);setState('문서 준비 완료','실제 팩스 송신을 시작할 수 있습니다.')}catch(e){F.page=null;$('#faxFileMeta').textContent=e.message;setState('문서 변환 실패',e.message)}}
async function sendControl(fr,label){log(label+' V.21 전송');await T.sendV21(F.ctx,fr);await delay(90)}
function showReceived(page){if(F.receivedUrl)URL.revokeObjectURL(F.receivedUrl);F.receivedUrl=URL.createObjectURL(page.blob);const name='received-fax-'+new Date().toISOString().replace(/[:.]/g,'-')+'.png';$('#download').href=F.receivedUrl;$('#download').download=name;$('#resultName').textContent=name;$('#resultType').textContent='image/png';$('#resultSize').textContent=Math.ceil(page.blob.size/1024)+' KB';$('#resultVerify').textContent='T.30 MCF · T.4 MH 복원';$('#resultTitle').textContent='팩스 페이지를 받았습니다';$('#resultModal').classList.remove('hidden')}
async function beginTcfReceive(){F.state='rx-tcf';F.rxCapture=new R.Capture(F.ctx.sampleRate,'tcf');setState('TCF 수신 중','V.27ter 2400bps 훈련과 1.5초 테스트 데이터를 검사합니다.');log('V.27ter TCF 캡처 시작');F.rxCapture.onDone=async samples=>{F.rxCapture=null;try{const d=R.demodulate(samples,F.ctx.sampleRate),test=d.bits.slice(0,Math.min(d.bits.length,3600)),zero=test.filter(b=>b===0).length/Math.max(1,test.length);log(`TCF 복조 · 0비트 ${(zero*100).toFixed(0)}%`);if(test.length<1000||zero<.72)throw Error('TCF 품질 부족');await sendControl(T.frame(T.FCF.CFR),'CFR');F.state='rx-page';setState('페이지 수신 대기','CFR을 보냈습니다. V.27ter 페이지 캐리어를 기다립니다.');startPageCapture()}catch(e){log('TCF 실패 · '+e.message);await sendControl(T.frame(T.FCF.FTT),'FTT');F.state='rx-training-failed';setState('훈련 실패(FTT)','TCF를 안정적으로 복조하지 못해 재훈련을 요청했습니다.')}}}
function startPageCapture(){F.rxCapture=new R.Capture(F.ctx.sampleRate,'page');F.rxCapture.onDone=samples=>{F.rxCapture=null;F.state='rx-decode';setState('페이지 복원 중','V.27ter 비트를 T.4 MH 이미지로 변환하고 있습니다.');log('페이지 캐리어 종료 · T.4 복원 시작');F.decodePromise=R.decodePage(samples,F.ctx.sampleRate).then(p=>{F.pendingPage=p;F.state='rx-wait-eop';log(`페이지 복원 성공 · 1728×${p.height}`);setState('페이지 복원 완료','EOP를 기다린 뒤 정상 수신 확인(MCF)을 보냅니다.');return p}).catch(e=>{F.pendingPage=null;F.state='rx-page-error';log('페이지 복원 실패 · '+e.message);setState('페이지 복원 실패',e.message);throw e})}}
async function onFrame(fr){const type=fr[2]&0xfe,name=T.NAMES[type]||('0x'+type.toString(16));log(`V.21 ${name} 수신 (${fr.length}B)`);$('#faxFreq').textContent='V.21 '+name;if(F.role==='tx'){if(type===T.FCF.DIS&&(F.state==='calling'||F.state==='wait-dis')){stopTone();F.state='negotiating';setState('DIS 수신','2400bps · T.4 1D 조건으로 DCS를 전송합니다.');await sendControl(T.makeDCS(),'DCS');await delay(75);setState('TCF 훈련 전송','V.27ter 2400bps 훈련 확인 신호를 전송합니다.');log('V.27ter TCF 시작');await T.sendV27(F.ctx,[],true);F.state='wait-cfr';setState('CFR 대기','상대 팩스의 훈련 성공 응답을 기다립니다.');return}if(type===T.FCF.CFR&&F.state==='wait-cfr'){F.state='page';setState('페이지 전송 중',`T.4 MH ${F.page.width}×${F.page.height} · V.27ter 2400bps`);log('CFR 수신 · 페이지 캐리어 시작');await T.sendV27(F.ctx,F.page.bits,false);await delay(250);F.state='wait-mcf';await sendControl(T.frame(T.FCF.EOP),'EOP');setState('MCF 대기','상대 팩스가 페이지를 정상 수신했는지 확인 중입니다.');return}if(type===T.FCF.FTT&&F.state==='wait-cfr'){F.state='failed';setState('훈련 실패(FTT)','전화망에서 V.27ter 훈련이 통과하지 못했습니다.');log('FTT 수신');return}if(type===T.FCF.MCF&&F.state==='wait-mcf'){await sendControl(T.frame(T.FCF.DCN),'DCN');F.state='done';setState('팩스 전송 완료','상대 팩스에서 MCF(정상 수신 확인)를 받았습니다.');log('MCF 수신 · 실제 팩스 전송 완료');return}}
if(F.role==='rx'){if(type===T.FCF.DCS&&F.state==='wait-dcs'){stopDisRetry();setState('DCS 수신','상대 송신기의 전송 조건을 확인했습니다. TCF를 받습니다.');log('DCS 해석 완료 · V.27ter TCF 대기');beginTcfReceive();return}if(type===T.FCF.EOP&&['rx-page','rx-decode','rx-wait-eop','rx-page-error'].includes(F.state)){let ok=false;try{if(F.decodePromise)await F.decodePromise;ok=!!F.pendingPage}catch{}if(ok){await sendControl(T.frame(T.FCF.MCF),'MCF');showReceived(F.pendingPage);F.state='rx-done';setState('팩스 수신 완료','페이지를 복원했고 MCF 정상 수신 확인을 보냈습니다.');log('EOP → MCF · 실제 페이지 수신 완료')}else{await sendControl(T.frame(0x4c),'RTN');F.state='rx-page-error';setState('페이지 오류(RTN)','페이지를 완전히 복원하지 못해 재전송을 요청했습니다.');log('EOP → RTN')}return}if(type===T.FCF.DCN){stopDisRetry();log('DCN 수신 · 통신 종료');if(F.state==='rx-done')setState('팩스 수신 완료','상대 송신기가 정상적으로 연결을 종료했습니다.');return}}
}
async function startTx(){if(!F.page)throw Error('먼저 JPG/PNG/WebP 이미지를 선택해 팩스 페이지로 변환하세요.');setState('마이크 준비 중','송신과 동시에 상대 팩스 응답을 듣기 위해 마이크를 엽니다.');await openAudio();F.role='tx';F.state='calling';F.cng=F.ced=0;stopTone();setState('팩스 호출 중','마이크가 활성화되었습니다. 실제 팩스 번호로 전화 연결 후 스피커폰 상태를 유지하세요. CNG를 보내며 DIS를 기다립니다.');log('실제 FAX TX 시작');const pulse=async()=>{if(F.state!=='calling')return;await tone(1100,.5);log('CNG 1100 Hz')};pulse();F.timer=setInterval(pulse,3500);$('#faxStop').classList.remove('hidden')}
async function startRx(){if(!R)throw Error('팩스 페이지 수신 모듈이 로드되지 않았습니다.');setState('마이크 준비 중','팩스 호출을 듣기 위해 마이크를 엽니다.');await openAudio();F.role='rx';F.cng=F.ced=0;F.rxCapture=null;F.decodePromise=null;F.pendingPage=null;stopDisRetry();$('#faxStop').classList.remove('hidden');log('실제 FAX RX 시작');setState('팩스 응답 시작','전화가 연결된 것으로 보고 표준 CED와 DIS 응답을 시작합니다.');await delay(250);await answerAsFax()}
async function answerAsFax(){if(F.busy)return;F.busy=true;try{F.state='answering';setState('팩스 응답 중','CED 2100 Hz 응답음을 3초간 전송합니다.');log('회선 연결 후 무음 구간 완료');await tone(2100,3);log('CED 2100 Hz 3초');await delay(100);F.state='wait-dcs';setState('DCS 대기','DIS를 전송하고 상대 송신기의 DCS를 기다립니다.');let attempt=0;const sendDis=async()=>{if(F.role!=='rx'||F.state!=='wait-dcs')return;attempt++;log(`DIS 전송 시도 ${attempt}/3`);await sendControl(T.makeDIS(),'DIS');if(F.role==='rx'&&F.state==='wait-dcs'&&attempt<3)F.disRetry=setTimeout(sendDis,650)};await sendDis()}finally{F.busy=false}}
async function sendCed(){await openAudio();await tone(2100,3);log('CED 수동 전송')}
function stop(){stopTone();stopDisRetry();F.rxCapture=null;F.decodePromise=null;if(F.scriptNode)F.scriptNode.onaudioprocess=null;F.stream?.getTracks().forEach(t=>t.stop());try{F.ctx?.close()}catch{}F.ctx=F.stream=F.src=F.node=F.silent=F.scriptNode=F.decoder=null;F.role=null;F.state='idle';micStatus('마이크: 꺼짐');$('#faxStop').classList.add('hidden');setState('중지됨','팩스 오디오 세션을 종료했습니다.');log('FAX Lab 중지')}
$('#faxTxStart')?.addEventListener('click',()=>startTx().catch(e=>{micStatus('마이크: 오류');setState('시작 실패',e.message);log('시작 실패 · '+e.message)}));$('#faxRxStart')?.addEventListener('click',()=>startRx().catch(e=>{micStatus('마이크: 오류');setState('시작 실패',e.message);log('시작 실패 · '+e.message)}));$('#faxSendCed')?.addEventListener('click',()=>sendCed().catch(e=>setState('전송 실패',e.message)));$('#faxStop')?.addEventListener('click',stop);$('#faxFile')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)prepareFile(f)});
})();